baseURL = "/"
languageCode = "en"
title = "Hugo Ava Theme"
theme = "hugo-theme-ava"
paginate = 7
mainSections = "post"

[outputs]
  home = ["HTML", "humanstxt"]
  
  [outputFormats.humanstxt]
      baseName = "humans"
      isPlainText = true
      mediaType = "text/plain"

[languages]
  [languages.en]
      languageName = "English"

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"
    
[params]
  ga_id=""
  mainSections = ["post"]
  disqus = "xxxxxxx"
  defaultImage = "https://raw.githubusercontent.com/jmau111/hugo-theme-ava/main/images/default.jpeg"

  [params.meta_tags]
    meta_description = "Ava is a light theme for your blog with essential features you might dig in."
    meta_og_title = "Hugo Ava Theme"
    meta_og_sitename = "Hugo Ava Theme"
    meta_og_type = "website"
    meta_og_url = "https://jmau111.github.io/hugo-theme-ava-demo"
    meta_og_image = "https://raw.githubusercontent.com/jmau111/hugo-theme-ava/main/images/default.jpeg"
    meta_og_description = "Ava is a light theme for your blog with essential features you might dig in."
    meta_twitter_card = "summary"
    meta_twitter_site = "@gohugoio"
    meta_twitter_creator = "@gohugoio"
    
 [params.humans_txt]
    dev_team = ""
    dev_github = ""
    thanks = ""
    standards = ""
    software = ""
    other_notes = ""
    
[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        tabWidth = 4
        noClasses = false
        pygmentsUseClasses = true
        pygmentsCodefences = true

    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true   

    [markup.blackFriday]
        angledQuotes = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Archives"
    url = "/posts/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
